import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

import NavigationBar from "@/components/NavigationBar";
import Footer from "@/components/Footer";

const poppins = Poppins({
	weight: ["400", "500"],
	subsets: ["latin"],
	fallback: ["sans-serif"],
});

export const minecraft = localFont({
	src: "../assets/fonts/Minecraft.otf",
	fallback: ["sans-serif"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={poppins.className}>
				<NavigationBar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
